### PR TITLE
fix: add __init__.py so pytest works

### PR DESCRIPTION
**Pull request by okeyokoro**
was getting

```
Traceback:
tests/step_defs/test_cucumbers_steps.py:3: in <module>
    from cucumbers import CucumberBasket
E   ModuleNotFoundError: No module named 'cucumbers
```

### CODE REVIEW

**Comment by AndyLPK247** [comment]
Hello! This doesn't make sense to me. **pytest** should _not_ need an __init__.py file to run tests. I'm very hesitant to add it to this example project. Could you please show the commands you used to invoke pytest, your paths, and your versions?

**Comment by okeyokoro** [comment]
steps to re-produce:

```sh
git clone git@github.com:AndyLPK247/tau-pytest-bdd.git

pipenv shell

pipenv install

pipenv run pytest

# get error

# -----------------
# steps to resolve
# -----------------

touch tests/__init__.py

pipenv run pytest
```

screenshots:

Screen Shot 2020-01-15 at 12 42 53 PM
Screen Shot 2020-01-15 at 12 44 20 PM

**Comment by okeyokoro** [comment]
P.S. thanks for making the awesome course

i'm having lots of fun playing with `pytest_bdd` 🙂

**Comment by AndyLPK247** [comment]
@okeyokoro - I'm glad to hear that you like the course!

Can you please try this command to invoke pytest?
`pipenv run python -m pytest`

Typically, it is a best practice to run "python -m pytest" instead of just "pytest".

**Comment by okeyokoro** [comment]
`pipenv run python -m pytest`

^ worked!

---

> Typically, it is a best practice to run "python -m pytest" instead of just "pytest".

^ learned this today

thanks for taking out the time!

---

i'll go ahead and close this pr

**Pull request closed without merging**
